language: php
sudo: required
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - RUN_PHPSTAN="FALSE"
  matrix:
    - LOWEST_DEPS=""
    - LOWEST_DEPS="--prefer-lowest"

matrix:
  include:
  - name: 'PHPStan'
    php: 7.2
    env: RUN_PHPSTAN="TRUE"

install:
  - if [ $RUN_PHPSTAN == "TRUE"  ]; then composer require --dev phpstan/phpstan:^0.12; fi

before_script:
  - composer update --prefer-source $LOWEST_DEPS

script:
  - if [ $RUN_PHPSTAN == "FALSE"  ]; then ./bin/php-cs-fixer  fix --dry-run --diff; fi
  - if [ $RUN_PHPSTAN == "FALSE"  ]; then ./bin/phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.xml; fi
  - if [ $RUN_PHPSTAN == "TRUE"  ]; then ./bin/phpstan.phar analyse -c phpstan.neon lib; fi

after_success:
- bash <(curl -s https://codecov.io/bash)

cache: vendor
